# -*- coding: utf-8 -*-
"""Request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvD026-pnCOCObLbhSU9FrllVTD_ExPP
"""

import requests

def current_weather_and_forecast():
    API_URL ='http://api.weatherapi.com/v1'
    API_Key = 'cbfd0b0894b94b78b00195838210512'
    API_city='q=London'
    API_method = '/current.json?'
    API_forecast_method = '/forecast.json?'
    current_response=requests.get(API_URL+API_method+'key='+API_Key+'&'+API_city)
    forecast_response=requests.get(API_URL+API_forecast_method+'key='+API_Key+'&'+API_city)
    print('Current weather in London:' + str(current_response.content))
    print('Weather forecast for London:' + str(forecast_response.content))


current_weather_and_forecast()